### PR TITLE
Extend word dictionary

### PR DESCRIPTION
**Pull request by drepram**
Words added :

- alright
- change
- start

Please correct me if something is wrong.

### CODE REVIEW

**Comment by ariya** [comment]
Thanks @drepram. But please add just one word at a time. And also the word is added as part of the test (see `test/test.js`).

**Comment by drepram** [comment]
Would you want me to reduce the changes I've made? I don't really understand what you're asking me to do here.

**Comment by ariya** [comment]
Don't simply add words to the dictionary. Implement an unmixing feature (which has the side effect to modifying the dictionary). Check all previous commits (e.g. 9af997f1).

**Comment by drepram** [comment]
I've simplified the PR into just one word and two forms of how the word would be used. Tests added for both forms.

**Comment by ariya** [comment]
Please squash all commits into one commit.

**Comment by drepram** [comment]
Squashed. Please take a look.

**Comment by ariya** [comment]
Still doesn't look it squashed (8 commits).

**Comment by drepram** [comment]
Commits have been squashed/simplified into one commit. Please take a look.

**Comment by ariya** [comment]
There are still unnecessary file mod/permission change (100644 → 100755). Please keep them the same.

**Comment by drepram** [comment]
I've fixed the permission issue, please take a look.

**Comment by ariya** [comment]
Awesome, thank you @drepram!

**Comment by drepram** [comment]
Thank you, it's my pleasure @ariya.

**Pull request merged**
